services:
  mongo:
    image: mongo:latest
    container_name: ids-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: ids-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data: